export const API_LOAD_NEWS_REQUEST = 'API_LOAD_NEWS_REQUEST'
export const API_LOAD_NEWS_REQUEST_SUCCESS = 'API_LOAD_NEWS_REQUEST_SUCCESS'
export const API_LOAD_NEWS_REQUEST_ERROR = 'API_LOAD_NEWS_REQUEST_ERROR'

