export const API_LOAD_SEARCH_NEWS = 'API_LOAD_SEARCH_NEWS';
export const API_LOAD_SEARCH_NEWS_SUCCESS = 'API_LOAD_SEARCH_NEWS_SUCCESS';
export const API_LOAD_SEARCH_NEWS_ERROR = 'API_LOAD_SEARCH_NEWS_ERROR'
