export const API_LOAD_CATEGORY_NEWS = 'API_LOAD_CATEGORY_NEWS';
export const API_LOAD_CATEGORY_NEWS_SUCCESS = 'API_LOAD_CATEGORY_NEWS_SUCCESS';
export const API_LOAD_CATEGORY_NEWS_ERROR = 'API_LOAD_CATEGORY_NEWS_ERROR'